server {
  listen 80;

  add_header Strict-Transport-Security "max-age=31536000; includeSubDomains" always;
  add_header Content-Security-Policy "default-src 'none'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; font-src 'self' fonts.gstatic.com fonts.googleapis.com; connect-src 'self' *.gstatic.com gstatic.com fonts.googleapis.com; img-src 'self' data:; style-src 'self' 'unsafe-inline' fonts.googleapis.com; base-uri 'self'; form-action 'self'; frame-src 'self' blob:; frame-ancestors 'self'; manifest-src 'self'; worker-src 'self' blob:";
  add_header X-Frame-Options SAMEORIGIN always;
  add_header X-XSS-Protection "1; mode=block";
  add_header X-Content-Type-Options "nosniff";
  add_header Cache-Control "no-cache";
  add_header Pragma "no-cache";
  add_header Expired "0";
  add_header Referrer-Policy "strict-origin-when-cross-origin";
  add_header Permissions-Policy "geolocation=(),midi=(),sync-xhr=(),microphone=(),camera=(),magnetometer=(),gyroscope=(),fullscreen=(self),payment=()";

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  include /etc/nginx/extra-conf.d/*.conf;
}
